server:
  port: 8080
  allowOrigins:
    - "*"
  bodyLimit: "10M" # MiB
  timeout: 30 # Seconds

database:
  host: localhost
  port: 5432
  user: root
  password: toor
  dbname: tablegame
  sslmode: disable
  schema: public